In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import time

In [13]:
df=pd.DataFrame(columns=['Titles'])

In [14]:
driver=webdriver.Chrome()
driver.get('https://www.crossword.in/collections/books')
time.sleep(10)
author_elems = driver.find_elements(By.CLASS_NAME, 'product-item-author')
title_elems = driver.find_elements(By.CLASS_NAME, 'product-item-title')
# Add each element's text to the DataFrame
#For titles
for i in title_elems:
    length = len(df)
    df.loc[length] = [i.text]
#For authors
for index, elem in enumerate(author_elems):
    if index < len(df):
        df.at[index, 'Authors'] = elem.text

# Close the browser
driver.quit()

C:\Users\harsh\AppData\Local\Temp\ipykernel_4032\980136701.py:14: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Baek Sehee' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[index, 'Authors'] = elem.text

In [15]:
df

,Titles,Authors
0,I Want To Die But I Want To Eat Tteokbokki,Baek Sehee
1,Acts of God,Kanan Gill
2,Ikigai,Hector Garcia
3,Disney Monsters University Classic Storybook,Parragon Books Ltd
4,Atomic Habits: The Life-Changing Million Copy ...,James Clear
5,The Psychology Of Money,Chitra Divakaruni Banerjee
6,The Palace Of Illusions,Robert T. Kiyosaki
7,Rich Dad Poor Dad,NA
8,Desire 100 Of Literatures Sexiest Stories,Gaur Gopal Das
9,Energize Your Mind,Chaitanya Charan
10,Gita Wisdom Through Quotes,Alex Michaelides
11,The Silent Patient: Crossword Special Edition,K.A. Tucker
12,The Simple Wild (The Simple Wild Book 1),Paulo Coelho
13,The Alchemist,Satyarth Nayak
14,Mahagatha: 100 Tales from the Puranas,Swapnil Pandey
15,Balidan: Stories Of Indian'S Greatest Para Spe...,Gaur Gopal Das
16,Life's Amazing Secrets,Paulo Coelho
17,Alchemist (Hindi),Khaled Hosseini
18,The Kite Runner,Robert Greene
19,The 48 Laws Of Power,Walt Disney
20,The Silent Patient,Inc Archie Comic Publications
21,Disney Princess The Little Mermaid: Ariel Make...,"Murty, Sudha"
22,Betty Jumbo Comics The Archie Library 1,NaN
23,"Here, There and Everywhere",NaN

Could see that the authors where not matched properly to the book titles

In [11]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import time

# Initialize lists to store titles and authors
titles = []
authors = []

# Initialize the web driver
driver = webdriver.Chrome()
driver.get('https://www.crossword.in/collections/books')

# Allow some time for the page to load
time.sleep(10)

# Find all div elements with the class 'result-product-item-info'
product_info_divs = driver.find_elements(By.CLASS_NAME, 'result-product-item-info')

# Iterate through each product info div and extract title and author
for product_info_div in product_info_divs:
    title_elem = product_info_div.find_element(By.CLASS_NAME, 'product-item-title')
    titles.append(title_elem.text)
    
    try:
        author_elem = product_info_div.find_element(By.CLASS_NAME, 'product-item-author')
        authors.append(author_elem.text)
    except:
        authors.append('NA')

# Close the browser
driver.quit()

# Create a DataFrame from the lists
new_df = pd.DataFrame({'Title': titles, 'Author': authors})

In [6]:
new_df

,Title,Author
0,I Want To Die But I Want To Eat Tteokbokki,Baek Sehee
1,Acts of God,Kanan Gill
2,Ikigai,Hector Garcia
3,Disney Monsters University Classic Storybook,Parragon Books Ltd
4,Atomic Habits: The Life-Changing Million Copy ...,James Clear
5,The Psychology Of Money,NA
6,The Palace Of Illusions,Chitra Divakaruni Banerjee
7,Rich Dad Poor Dad,Robert T. Kiyosaki
8,Desire 100 Of Literatures Sexiest Stories,NA
9,Energize Your Mind,Gaur Gopal Das
10,Gita Wisdom Through Quotes,Chaitanya Charan
11,The Silent Patient: Crossword Special Edition,Alex Michaelides
12,The Simple Wild (The Simple Wild Book 1),K.A. Tucker
13,The Alchemist,Paulo Coelho
14,Mahagatha: 100 Tales from the Puranas,Satyarth Nayak
15,Balidan: Stories Of Indian'S Greatest Para Spe...,Swapnil Pandey
16,Life's Amazing Secrets,Gaur Gopal Das
17,Alchemist (Hindi),Paulo Coelho
18,The Kite Runner,Khaled Hosseini
19,The 48 Laws Of Power,Robert Greene
20,The Silent Patient,NA
21,Disney Princess The Little Mermaid: Ariel Make...,Walt Disney
22,Betty Jumbo Comics The Archie Library 1,Inc Archie Comic Publications
23,"Here, There and Everywhere","Murty, Sudha"

Adding price to the dataframe

In [30]:
driver=webdriver.Chrome()
driver.get('https://www.crossword.in/collections/books')
price=driver.find_elements(By.CLASS_NAME,'wizzy-product-item-price')
for elem in price:
    print(elem.text)
driver.close()

₹399
₹339 ₹399 (15%)
₹467 ₹550 (15%)
₹249 ₹499 (50%)
₹679 ₹799 (15%)
₹339 ₹399 (15%)
₹424 ₹499 (15%)
₹509 ₹599 (15%)
₹647 ₹1,295 (50%)
₹299
₹296 ₹349 (15%)
₹599
₹550
₹339 ₹399 (15%)
₹509 ₹599 (15%)
₹299
₹299
₹350
₹509 ₹599 (15%)
₹849 ₹999 (15%)
₹339 ₹399 (15%)
₹295
₹647 ₹1,295 (50%)
₹212 ₹250 (15%)

we want first price only

In [12]:
driver=webdriver.Chrome()
driver.get('https://www.crossword.in/collections/books')
price=driver.find_elements(By.CLASS_NAME,'wizzy-product-item-price')
for index, elem in enumerate(price):
    if index < len(new_df):
        new_df.at[index, 'Price'] = elem.text.split(' ')[0]
driver.close()

C:\Users\harsh\AppData\Local\Temp\ipykernel_7636\537069769.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '₹399' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  new_df.at[index, 'Price'] = elem.text.split(' ')[0]

In [14]:
new_df

,Title,Author,Price
0,I Want To Die But I Want To Eat Tteokbokki,Baek Sehee,₹399
1,Acts of God,Kanan Gill,₹339
2,Ikigai,Hector Garcia,₹467
3,Disney Monsters University Classic Storybook,Parragon Books Ltd,₹249
4,Atomic Habits: The Life-Changing Million Copy ...,James Clear,₹679
5,The Psychology Of Money,NA,₹339
6,The Palace Of Illusions,Chitra Divakaruni Banerjee,₹424
7,Rich Dad Poor Dad,Robert T. Kiyosaki,₹509
8,Desire 100 Of Literatures Sexiest Stories,NA,₹647
9,Energize Your Mind,Gaur Gopal Das,₹299
10,Gita Wisdom Through Quotes,Chaitanya Charan,₹296
11,The Silent Patient: Crossword Special Edition,Alex Michaelides,₹599
12,The Simple Wild (The Simple Wild Book 1),K.A. Tucker,₹550
13,The Alchemist,Paulo Coelho,₹339
14,Mahagatha: 100 Tales from the Puranas,Satyarth Nayak,₹509
15,Balidan: Stories Of Indian'S Greatest Para Spe...,Swapnil Pandey,₹299
16,Life's Amazing Secrets,Gaur Gopal Das,₹299
17,Alchemist (Hindi),Paulo Coelho,₹350
18,The Kite Runner,Khaled Hosseini,₹509
19,The 48 Laws Of Power,Robert Greene,₹849
20,The Silent Patient,NA,₹339
21,Disney Princess The Little Mermaid: Ariel Make...,Walt Disney,₹295
22,Betty Jumbo Comics The Archie Library 1,Inc Archie Comic Publications,₹647
23,"Here, There and Everywhere","Murty, Sudha",₹212

Save extracted data to csv file

In [15]:
new_df.to_csv('books_extract.csv', index=False)